# Goals
- Review the features of numpy na python that are used in Course 1

In [2]:
import numpy as np
import time

# Useful Reference 
- NumPy Documentation including a basic introduction: NumPy.org
- A challenging feature topic: NumPy Broadcasting

# Python and Numpy
Python is the programming language we will be using in this course. It has a set of numeric data types and arithmetic operations. NumPy is a library that extends the base capabilities of python to add a richer data set including more numeric types, vectors, matrices, and many matrix functions. NumPy and python work together fairly seamlessly. Python arithmetic operators work on NumPy data types and many NumPy functions will accept python data types.

# Vector
## 3.1 Abstract
Vectors, as you will use them in this course, are ordered arrays of numbers. In notation, vectors are denoted with lower case bold letters such as x. The elements of a vector are all the same type. A vector does not, for example, contain both characters and numbers. The number of elements in the array is often referred to as the dimension though mathematicians may prefer rank. The vector shown has a dimension of n. The elements of a vector can be referenced with an index. In math settings, indexes typically run from 1 to n. In computer science and these labs, indexing will typically run from 0 to n-1. In notation, elements of a vector, when referenced individually will indicate the index in a subscript, for example, the 0^th element, of the vector x is x0. Note, the x is not bold in this case

## 3.2 Numpy Arrays
NumPy's basic data structure is an indexable, n-dimensional array containing elements of the same type (dtype). Right away, you may notice we have overloaded the term 'dimension'. Above, it was the number of elements in the vector, here, dimension refers to the number of indexes of an array. A one-dimensional or 1-D array has one index. In Course 1, we will represent vectors as NumPy 1-D arrays.
- 1-D array, shape (n): n elements indexed [0] through [n-1]

## 3.3 Vector Creation
Data creation routines in NumPy will generally have a first parameter which is the shape of the object. This can either be a single value for a 1-D result or a tuple (n,m,...) specifying the shape of the result. Below are examples of creating vectors using these routines

In [6]:
a = np.zeros(4); print(f"np.zeros(4):a={a}, a shape={a.shape}, a data type = {a.dtype}")
a = np.zeros((4,)); print(f"np.zeros(4):a={a}, a shape={a.shape}, a data type = {a.dtype}")
a =np.random.random_sample(4); print(f"np.zeros(4):a={a}, a shape={a.shape}, a data type = {a.dtype}")

np.zeros(4):a=[0. 0. 0. 0.], a shape=(4,), a data type = float64
np.zeros(4):a=[0. 0. 0. 0.], a shape=(4,), a data type = float64
np.zeros(4):a=[0.70936132 0.49224833 0.78783667 0.79275273], a shape=(4,), a data type = float64


Some data creation routines do not take a shape tuple

In [9]:
a = np.arange(4,); print(f"np.zeros(4):a={a}, a shape={a.shape}, a data type = {a.dtype}")
a = np.random.rand(4); print(f"np.zeros(4):a={a}, a shape={a.shape}, a data type = {a.dtype}")

np.zeros(4):a=[0 1 2 3], a shape=(4,), a data type = int32
np.zeros(4):a=[0.02248313 0.72266481 0.06282772 0.85078608], a shape=(4,), a data type = float64


values can be specified manually as well

In [11]:
a = np.array([5,4,3,2]); print(f"np.zeros(4):a={a}, a shape={a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.zeros(4):a={a}, a shape={a.shape}, a data type = {a.dtype}")

np.zeros(4):a=[5 4 3 2], a shape=(4,), a data type = int32
np.zeros(4):a=[5. 4. 3. 2.], a shape=(4,), a data type = float64


# 3.4 Operations on Vectors
## 3.4.1 Indexing
Elements of vectors can be accessed via indexing and slicing. NumPy provides a very complete set of indexing and slicing capabilities. We will explore only the basics needed for the course here. Reference Slicing and Indexing for more details.
Indexing means referring to an element of an array by its position within the array.
Slicing means getting a subset of elements from an array based on their indices.
NumPy starts indexing at zero so the 3rd element of an vector a
 is a[2]

In [14]:
#vector indexing operations on 1-D vectors
a = np.arange(10); print(a)
print(a[2].shape)
print(a[-1])

[0 1 2 3 4 5 6 7 8 9]
()
9


## 3.4.2 Slicing
Slicing creates an array of indices using a set of three values (start:stop:step). A subset of values is also valid. Its use is best explained by example:

In [15]:
a = np.arange(10)
print(a[2:7:1])
print(a[2:7:2])
print(a[3:])
print(a[:3])

[2 3 4 5 6]
[2 4 6]
[3 4 5 6 7 8 9]
[0 1 2]


## Single vector operations
There are a number of useful operations that involve operations on a single vector.

In [17]:
a = np.array([1,2,3,4])
b = -a
print(b)
print(np.sum(a))
print(np.mean(a))
b = a**2
print(b)

[-1 -2 -3 -4]
10
2.5
[ 1  4  9 16]


## 3.4.4 Vector Vector element-wise operations


In [20]:
a = np.array([1,2,3,4])
b = np.array([-1,-2,3,4])
print(a+b)
c = = np.array([1,2])
#print(a+c) # error

SyntaxError: invalid syntax (3135573947.py, line 4)

## 3.4.5 Scalar Vector operations

In [21]:
a =np.array([1,2,3,4])
b = 5*a
print(b)

[ 5 10 15 20]


# 3.4.6 Vector Vector dot product 
This can make you calculate faster and more efficient

In [23]:
def my_dot(a, b): 
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [25]:
np.random.seed(1)
a = np.random.rand(100000000)
b = np.random.rand(100000000)

tic =time.time()
c= np.dot(a,b)
toc = time.time()
print(toc-tic)

tic = time.time()
c = my_dot(a, b)
toc = time.time()

print(toc-tic)

del(a); del(b) # remove these big arrays from memory

0.9676716327667236
105.42969870567322


## Vector Vector operations in Course 1

In [4]:
X = np.array([[1], [2], [3], [4]])
w = np.array([2])
c = np.dot(X[1], w)

print(X[1].shape)
print(w.shape)
print(c.shape)

(1,)
(1,)
()


## Matrix Creation 

In [5]:
a =np.zeros((1, 5))
print(a.shape, a)

(1, 5) [[0. 0. 0. 0. 0.]]


## Indexing 

In [7]:
a =np.arange(6).reshape(-1, 2)

## Slicing

In [8]:
a = np.arange(20).reshape(-1, 10)
print(a[:,2:7:2])

[[ 2  4  6]
 [12 14 16]]
